version: '3.8'

services:
  datacollect0r_bot:
    build: .
    container_name: datacollect0r_bot
    env_file:
      - .env 
    volumes:
      - db_data:/app/DataCollect0r_Bot
    restart: unless-stopped

volumes:
  db_data:
